### ISSUE TITLE
FAIcon is not inline with system icons on UIBarItem 

### ISSUE THREAD

**Issue by jaredStef** [Vaberer/Font-Awesome-Swift#19]
![screen shot 2015-12-09 at 7 06 47 pm](https://cloud.githubusercontent.com/assets/7342882/11702882/4f488a3c-9ea8-11e5-8c27-aa88a5272f43.png)
As you can see the icon is not centered with system icons. I am using the following code. 
<code>settingsBarButtonItem.setFAIcon(FAType.Gear, iconSize: 26)</code>

**Comment by skrosoft** [comment]
Same problem here :( jared, have you found a solution?

**Comment by jaredStef** [comment]
Not yet, but I have an app due mid January and have to figure it out :/

**Comment by jaredStef** [comment]
If you use the UIImage initalizer it will be inline, but smaller or larger than usual and still look odd. 
<code>settingsBarButtonItem.image = UIImage(icon: FAType.FAGear, size: CGSize(width: 34, height: 34))</code>

**Comment by jaredStef** [comment]
@skrosoft I fixed it. My solution was to set the left edge inset and set the image property wile using the convenience initalizer included with Font Awesome. 
<code>settingsBarButtonItem.image = UIImage(icon: FAType.FAGear, size: CGSize(width: 34, height: 34))
settingsBarButtonItem.imageInsets = UIEdgeInsets.init(top: 0, left: -15, bottom: 0, right: 0)</code>

**Comment by skrosoft** [comment]
Hi Jared, thank you, this work very well. I was following another solution I found on Internet but this one is much better.

**Comment by Vaberer** [comment]
Hello,

I was experiencing with this issue and tested it with two font awesome bar buttons and it works.
<img width="571" alt="screen shot 2016-03-22 at 7 04 16 pm" src="https://cloud.githubusercontent.com/assets/8090436/13962370/e83515bc-f060-11e5-8336-d5a4a7239569.png">

Since the content in `UIBarButtonItem` is just a text, it's not possible to adjust a position. So using system icons with this library should be use via image :)

Anyway thanks for the remark. I'll add this hack into a readme file.
